version: "3"
services:
  postgres:
    networks:
      - concurrent
    image: postgres:14-alpine
    ports:
      - 5431:5432
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=employee
    volumes:
      - /var/lib/postgresql/data

  app:
    networks:
      - concurrent
    depends_on:
      - postgres
networks:
  concurrent:
    driver: bridge
