version: "3"
services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5431:5432
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nfra
    volumes:
      - /var/lib/postgresql/data

